### ISSUE TITLE
Proper Pytorch version

### ISSUE THREAD

**Issue by rndm-jpg** [parasj/contracode#24]
First of all, thanks for sharing the impressive work!

We were trying to get the finetuning for downstream task working, but got the following issue
```
torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'encoder'
```

It's quite likely that we were using the incorrect version of Pytorch (or maybe other dependencies).

Would you kindly share the proper version of the dependency required to run the project?

Cheers

**Comment by parasj** [comment]
Hi @rndm-jpg,

Apologies for the delay! We used PyTorch 1.6.0. If you can share a larger error trace, I can help debug further.

Thanks,
Paras
