### ISSUE TITLE
ask help for the codeclone dataset

### ISSUE THREAD

**Issue by LeeSureman** [parasj/contracode#27]
great work! I need some help of your codeclone dataset. If you do not mind spend a little time and help me figure out it , I will be very appreciated to you. I download it by the "scripts/download_data.py" in your repo (codeclone/full_data.json.gz) , but I do not know wether it is the dataset used in "4.1 Evaluating Functionality and Robustness: Zero-shot Code Clone Detection" in your paper. I see the "split" function in "representjs/clone_detection.py", so I'm confused... And for the 2065 pairs you mention in your paper, ( also in 4.1) , is it from the same dataset? and how to get it? If you do not mind spend a little time and help me figure out it , I will be very appreciated to you.

**Comment by parasj** [comment]
@LeeSureman I haven't been following the issues on this project, but I would love to help. Are you still facing these issues when running the code?

I'm looking into the dataset we uploaded as `full_data.json.gz` and it does seem to be incompatible with `clone_detection.py`.

**Comment by parasj** [comment]
I apologize for the delay in reply!

**Comment by LeeSureman** [comment]
Thank you for your response. We needed to compare your model on the codeclonedetection task when we submit our paper to ACL 2022. Finally we cancel the comparison. But we will still consider your model and your released dataset in future work.

**Comment by parasj** [comment]
Best of luck with your submission! Closing this issue, but please email or reopen the PR if needed.
