### ISSUE TITLE
code embedding

### ISSUE THREAD

**Issue by Dear123132** [parasj/contracode#28]

**Comment by parasj** [comment]
@Dear123132 I see the comment was edited to be empty so I had disregarded this issue, but I see your original question was: Can your project code generate code embedding? Generate code embedding like codebert and graphcodebert

Yes! ContraCode in fact is meant to learn better code embeddings than CodeBERT while distilling the property of functional invariance. You can use the representation without the linear projection head to do so. Please reply if you have difficulty extracting this embedding from the model.
