### ISSUE TITLE
Python functions extension

### ISSUE THREAD

**Issue by alexkarargyris** [parasj/contracode#29]
@parasj Is it your code applicable to Python language function? More precisely can the automated source to source compiler transformation be used for Python beyond js language?

**Comment by parasj** [comment]
Hi @alexkarargyris -- currently, we implement support for source-to-source transformations for Javascript and Typescript. We used the babel transpiler to implement these passes. We don't have plans to extend this to Python but it would likely be possible via source-to-source converters like https://docs.python.org/3/library/2to3.html or via AST manipulation (see this guide https://greentreesnakes.readthedocs.io/en/latest/).

**Comment by parasj** [comment]
If you would like to use the ContraCode modeling approach over Python, the rest of the PyTorch code can likely be used mostly unmodified. However, you would need to modify the dataloader https://github.com/parasj/contracode/blob/master/representjs/data/augmented_dataset.py
