### ISSUE TITLE
data.zip

### ISSUE THREAD

**Issue by jinchengyang98** [parasj/contracode#30]
Failed to decompress the data.zip file in the cloud disk. Is there any solution

**Comment by parasj** [comment]
Hi, can you provide more details e.g. which file you are downloading and how big your filesystem is (e.g. run `df -h`)?

**Comment by parasj** [comment]
You may not have enough local disk space on EBS if you ran this on AWS. You should try resizing the disk to be larger.

**Comment by jinchengyang98** [comment]
Hello, the author, I tried to decompress this compressed package in the ubuntu22.04 LTS system. The total size of the disk is 651G, and the remaining size is 395G。When I try to decompress, the system prompts' Damage Zip Archive '.

**Comment by parasj** [comment]
I am able to decompress the file locally. If you have sufficient EBS space for the file, the download may have corrupted the ZIP file.

Can you compute an md5sum of the file: `md5sum data.zip`

I computed `a5ef7f070b326370fd0518bc9de63455` locally.

**Comment by jinchengyang98** [comment]
Thank you, sir. I solved this problem. 
I had problems downloading data.zip with ubuntu, but when I unzipped data.zip with windows11, there was no problem.
 My md5 code is the same as yours.

**Comment by jinchengyang98** [comment]
Thank you for your help！

**Comment by parasj** [comment]
Glad it worked!
