### ISSUE TITLE
Cannot obtain the checkpoint 

### ISSUE THREAD

**Issue by MingZhang7** [parasj/contracode#31]
I follow the README to 

`Download the data subfolder from [this Google Drive link](https://drive.google.com/drive/folders/153pZfKPcr1-l8VaDPys29b1ElGLuoq3M?usp=sharing) and place at the root of the repository. This folder contains training and evaluation data, vocabularies and model checkpoints.`

However, I do not fine the checkpoints and only the data.zip.

![image](https://user-images.githubusercontent.com/118048331/202175193-8b1e8aad-4566-431c-a98c-3d18b813f61c.png)

How can I obtain the checkpoint?

Thanks

**Comment by ajayjain** [comment]
@MingZhang7 Apologies for the delay in getting back to you. Checkpoints are located in the "data" subfolder of that google drive folder. This is a direct link: https://drive.google.com/drive/folders/1Yw9lMLxGNKPDK3zaKuQdrAw7KQqyOu5y
